// Snapshot tests for tofu-summarize — terragrunt fixtures
// (single-unit `terragrunt run` and multi-unit `run --all`),
// generated by nix run .#create-terragrunt-inputs.
import describeFixtures from "./fixture-snapshots";

describeFixtures("terragrunt");
